### ISSUE TITLE
Configure logs

### ISSUE THREAD

**Issue by torives** [cartesi/rollups-node#116]
## 📚 Context
We must log its events to better understand what is happening inside the Go supervisor. This is currently being done without any control or structure using the `fmt` package, which may lead to confusion as the project gets more complex over time.

## ✔️ Solution
Create a simple `logger` package to wrap the native `log` and provide log levels and configuration via environment variables

**Comment by endersonmaia** [comment]
If you want some structured logging capability, I suggest taking a look at https://github.com/rs/zerolog

**Comment by torives** [comment]
> If you want some structured logging capability, I suggest taking a look at https://github.com/rs/zerolog

Thanks for the suggestion, @endersonmaia! We're keeping it simple for now, trying to add as few dependencies as possible. But if the need arises, we'll certainly consider it.
