### ISSUE TITLE
Separating services and libraries

### ISSUE THREAD

**Issue by renan061** [cartesi/rollups-node#13]
## 📚 Context

The offchain workspace has directories for services and libraries at the same hierarchical level.
It would be nice to distinguish them for readability purposes.

## ✔️ Solution

We can have two workspaces inside the offchain folder, one for services and one for libraries.
They would have to reference each other statically.

We are accepting suggestions for other possible solutions.

## 📈 Subtasks

Undetermined.

**Comment by gligneul** [comment]
We will migrate to Go
