### ISSUE TITLE
Make Rollups 1.2 work in examples

### ISSUE THREAD

**Issue by gligneul** [cartesi/rollups-node#131]
Depends on #135

Test branch available at https://github.com/cartesi/rollups-examples/tree/feature/rollups-node-1.2

**Comment by marcelstanley** [comment]
# Integration tests

| Example | Test result |
|---|---|
| `echo-cpp` |  PASS |
| `echo-js` | PASS |
| `echo-low-level` | PASS |
| `echo-lua` | PASS |
| `echo-cpp` | PASS |
| `echo-python` | PASS |

# Rollups 1.2 Test plan

## Test 1

**Steps:**

1. Send ONE valid input to DApp
2. Finish epoch

**Expected result**: Authority-claimer sends claim

## Test 2

**Steps:**

1. Send ZERO inputs to DApp
2. Finish epoch

**Expected result**: Authority-claimer DOES NOT send claim

# Test results

| Example | Test 1  | Test 2 |
|---|---|---|
| `auction` |  ? | ? |
| `calculator` |  ? | ? |
| `converter` |  ? | ? |
| `template` |  ? | ? |
| `echo-cpp` |  PASS | PASS |
| `echo-js` | PASS | PASS |
| `echo-low-level` | PASS | PASS |
| `echo-lua` | PASS | PASS |
| `echo-cpp` | PASS | PASS |
| `echo-python` | PASS | PASS |
| `echo-rust` | PASS | PASS |
| `erc20` | PASS | PASS |
| `knn` |  ? | ? |
| `m2cgen` |  ? | ? |
| `sqlite` |  ? | ? |

**Comment by gligneul** [comment]
@marcelstanley I have written down a few test cases for previous tests that I did. Could you check them out?

### Send one input and get result from graphql

    yarn start input send --payload hi

    curl 'http://localhost:4000/graphql' -H 'Accept-Encoding: gzip, deflate, br' -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Connection: keep-alive' -H 'DNT: 1' -H 'Origin: http://localhost:4000' --data-binary '{"query":"{\n  input(index: 0) {\n    index\n    status\n  }\n}\n"}' --compressed | jq

### Send more inputs and get result from graphql

    for i in $(seq 1 3); do yarn start input send --payload "hi $i"; done

    curl 'http://localhost:4000/graphql' -H 'Accept-Encoding: gzip, deflate, br' -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Connection: keep-alive' -H 'DNT: 1' -H 'Origin: http://localhost:4000' --data-binary '{"query":"# Write your query or mutation here\n\n{\n  inputs {\n    edges {\n      node {\n        index\n        status\n        payload\n      }\n    }\n  }\n}\n"}' --compressed | jq

### Get notices from GraphQL

    curl 'http://localhost:4000/graphql' -H 'Accept-Encoding: gzip, deflate, br' -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Connection: keep-alive' -H 'DNT: 1' -H 'Origin: http://localhost:4000' --data-binary '{"query":"{\n  notices {\n    edges {\n      node {\n        index\n        input {\n          index\n        }\n        payload\n      }\n    }\n  }\n}"}' --compressed | jq

### Finish epoch, get proof from GraphQL, and validate the notice

    curl --data '{"id":1337,"jsonrpc":"2.0","method":"evm_increaseTime","params":[864010]}' http://localhost:8545

    curl 'http://localhost:4000/graphql' -H 'Accept-Encoding: gzip, deflate, br' -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Connection: keep-alive' -H 'DNT: 1' -H 'Origin: http://localhost:4000' --data-binary '{"query":"{\n  notice(inputIndex: 0, noticeIndex: 0) {\n    payload\n    proof {\n\t\t\tcontext\n    }\n  }\n}"}' --compressed | jq

    # eventually the notice should be valid
    yarn start notice validate --input 0 --index 0

### Send input in the next epoch

    yarn start input send --payload "second epoch"

    # proof should be null
    curl 'http://localhost:4000/graphql' -H 'Accept-Encoding: gzip, deflate, br' -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Connection: keep-alive' -H 'DNT: 1' -H 'Origin: http://localhost:4000' --data-binary '{"query":"{\n  notice(inputIndex: 4, noticeIndex: 0) {\n    payload\n    proof {\n\t\t\tcontext\n    }\n  }\n}"}' --compressed | jq .data.notice

### Finish second epoch

    curl --data '{"id":1337,"jsonrpc":"2.0","method":"evm_increaseTime","params":[864010]}' http://localhost:8545

    # proof should be set eventually, with context ...0001
    curl 'http://localhost:4000/graphql' -H 'Accept-Encoding: gzip, deflate, br' -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Connection: keep-alive' -H 'DNT: 1' -H 'Origin: http://localhost:4000' --data-binary '{"query":"{\n  input(index: 4) {\n    index\n    status\n    notice(index: 0) {\n      payload\n      proof {\n\t\t\t\tcontext\n      }\n    }\n  }\n}\n"}' --compressed | jq .data.input

### Advance epoch time and send input after

    curl --data '{"id":1337,"jsonrpc":"2.0","method":"evm_increaseTime","params":[10000000]}' http://localhost:8545

    yarn start input send --payload "third epoch"

    # proof should be set eventually, with context ...0002
    curl 'http://localhost:4000/graphql' -H 'Accept-Encoding: gzip, deflate, br' -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Connection: keep-alive' -H 'DNT: 1' -H 'Origin: http://localhost:4000' --data-binary '{"query":"{\n  input(index: 5) {\n    index\n    status\n    notice(index: 0) {\n      payload\n      proof {\n\t\t\t\tcontext\n      }\n    }\n  }\n}\n"}' --compressed | jq .data.input

### Send inspect request with GET

    curl -s localhost:5005/inspect/ | jq
    curl -s localhost:5005/inspect/hi | jq

### Send inspect request with post

    curl -s -X POST -d 'hi' localhost:5005/inspect | jq -r .reports[0].payload | cut -b 3- | xxd -r -p

    echo deadbeef | xxd -r -p > payload.bin
    curl -s -X POST -d @payload.bin localhost:5005/inspect | jq
