### ISSUE TITLE
Add shell script `gen-devnet` to generate the Anvil state

### ISSUE THREAD

**Issue by gligneul** [cartesi/rollups-node#149]
## 📚 Context

We want to simplify the generation of the Anvil state for the devnet.

## ✔️ Solution

Create a new Go binary under `cmd/gen-devnet` responsible for building the Anvil state. This binary will:
- Receive the following command line parameters:
  - DApp machine template hash (used to deploy the dapp)
  - Path to the anvil state file output
  - Path to the deployment info file (we need a file that contains the addresses of the deployed contracts)
- Download the rollups contracts (see [`pkg/contracts/generate/main.go`](https://github.com/cartesi/rollups-node/blob/next/pkg/contracts/generate/main.go))
- Start Anvil in the background with `--dump-state` (https://github.com/foundry-rs/foundry/tree/master/crates/anvil)
- Deploy the rollups contracts using forge (https://book.getfoundry.sh/forge/deploying)
- Call the authority/history/dapp factory to deploy the authority, history, and DApp contracts using cast (https://book.getfoundry.sh/cast/)
- Stop anvil

We will run this command later inside a Dockerfile. So, it can be assumed that all necessary tools (e.g., foundry) are installed.

**Comment by marcelstanley** [comment]
This command depends on:
- having a machine template hash available
- ideally, using the same `salt` as sunodo when deploying DApps deterministically via factories and end up with the same contract addresses in the end.
