### ISSUE TITLE
Verify whether generated files are in sync

### ISSUE THREAD

**Issue by gligneul** [cartesi/rollups-node#183]
## 📚 Context

We are committing generated text files to the repo because it is more straightforward. However, if someone forgets to update the generated file, it will get out of sync.

I would rather not commit these files in CI or generate them on demand.

## ✔️ Solution

Add a CI job that generates the files and checks if they are out-of-sync. If that is the case, the person will be forced to fix their PR before merging it.

Currently, we generate files with:
- `go generate`
- `go run ./cmd/gen-docs`
- This file https://github.com/cartesi/rollups-node/blob/main/offchain/graphql-server/src/schema/generate_schema.rs

## 🐢 

Also, let's add an "auto-generated" warning to the files as discussed at https://github.com/cartesi/rollups-node/pull/170#discussion_r1413803041

**Comment by marcelstanley** [comment]
Also, let's add a "auto-generated" warning to the files as discussed at https://github.com/cartesi/rollups-node/pull/170#discussion_r1413803041

**Comment by gligneul** [comment]
We should probably set-up a `tools.go` file to track the Go tools we use with `go generate`. See https://marcofranssen.nl/manage-go-tools-via-go-modules
