### ISSUE TITLE
Use the metrics to test the Dispatcher

### ISSUE THREAD

**Issue by renan061** [cartesi/rollups-node#19]
## 📚 Context

The dispatcher's tests have a bunch of scaffolding code that can be cleaned up now that we have metrics.

## ✔️ Solution

Use the metrics to track the state in the tests and assert over them.

**Comment by gligneul** [comment]
Once we migrate to the [new architecture](https://github.com/cartesi/rollups-node/issues/101), retrieving metrics directly from the SQL database will be possible.
