### ISSUE TITLE
Upgrade state-fold's `tonic` version 

### ISSUE THREAD

**Issue by renan061** [cartesi/rollups-node#21]
## 📚 Context

The state-fold library is still using `tonic` 0.8 (in place of the newer 0.9).
For this reason, the `dispatcher` and the `state-server` have to use a different version than the rest of the project. 

## ✔️ Solution

Upgrade `tonic`'s version in the state-fold library and in the aforementioned packages.

**Comment by gligneul** [comment]
We won't do that because we will move to a new architecture in https://github.com/cartesi/rollups-node/issues/101
