### ISSUE TITLE
Update host-runner to use the `http-server` crate.

### ISSUE THREAD

**Issue by torives** [cartesi/rollups-node#22]
## 📚 Context

The new `http-server` provides a standard way to send metrics and also provides a ready-to-use health check. To simplify maintenance, we should replace the older health check implementation with the new one.

## ✔️ Solution

Use the newer health check implementation from the `http-server` crate.

**Comment by gligneul** [comment]
We won't do that because we will move to a new architecture in https://github.com/cartesi/rollups-node/issues/101
