### ISSUE TITLE
MNEMONIC is leaking in the logs

### ISSUE THREAD

**Issue by endersonmaia** [cartesi/rollups-node#223]
## 🙂 Expected behavior

What was expected?

When using `--tx-signing-mnemonic <TX_SIGNING_MNEMONIC>` or `--tx-signing-mnemonic-file <TX_SIGNING_MNEMONIC_FILE>`, their content should be hidden from logs since its considered sensitive information.

## 🫠 Actual behavior

What happened instead?

The MNEMONIC content should never be logged,

## 🧪 Minimal test case

Start a rollups-node using configuring the authority-claimer with `--tx-signing-mnemonic` and looking at the logs.

```
...
tx_signing_config: Mnemonic { mnemonic: "you should not be seeing this twelve words that are part of secret" account_index: None }
...
```

## 🌎 Environment

rollups-node:1.2.0

## ✔️ Possible solutions

Hide the MNEMONIC content from logs, like it was already done in previous versions.

**Comment by torives** [comment]
I suppose PR #203 will fix this via the `redact` property in the [Config.toml](https://github.com/cartesi/rollups-node/pull/203/files#diff-effb3966fa51e559d6cd98d496e76439c6e198fd19e99a7fb9dc105b390f6141R143) file.

@renan061 can you confirm this, please?
