### ISSUE TITLE
CI tests for the AWS KMS signer

### ISSUE THREAD

**Issue by renan061** [cartesi/rollups-node#24]
## 📚 Context

The tests for the AWS KMS signer must be executed manually due to authentication restrictions.
They are currently being ignored in the CI.

## ✔️ Solution

- We can try to mock what we need locally.
- We can add the necessary authentication to the CI.

We don't know which solution is more viable. We need to explore it further.

## 📈 Subtasks

- [x] Study the solutions and decide which one is more viable.
- [x] Tests for the AWS KMS signer running in the CI.

**Comment by gligneul** [comment]
I will close this issue because we will add the tests when re-implementing this feature in the Go node.
