### ISSUE TITLE
Reimplement dispatcher in Go

### ISSUE THREAD

**Issue by gligneul** [cartesi/rollups-node#257]
## 📚 Context

We should reimplement the dispatcher service in Go. Instead of being a separate service, it should be an internal service in Go that runs in a goroutine.

We should also evaluate whether we can use an off-the-shelf solution to index the Ethereum node. For instance, [subsquid](https://docs.subsquid.io/overview/) is a great candidate.

**Comment by marcelstanley** [comment]
Closed in favor of #320
