### ISSUE TITLE
Add POST inspect to HTTP API

### ISSUE THREAD

**Issue by gligneul** [cartesi/rollups-node#27]
## 📚 Context

Currently, the inspect HTTP API has only one endpoint that receives the payload in the request path. This is limiting because it is not possible to send binaries as a payload, and there is a size constraint to the size of the payload.

## ✔️ Solution

Add another endpoint to the inspect API that receives the payload in the body. This endpoint should be a POST because we shouldn't receive a body in an HTTP get request. We shouldn't remove the old endpoint; it might still be useful for those who encode the inspect payload as a path.

## 📈 Subtasks

- [x] Define POST inspect in the OpenAPI interfaces.
- [x] Add new endpoint to the inspect HTTP server.
- [x] Update tests
- [ ] Update documentation

**Comment by marcelstanley** [comment]
PRs:

- #52 
- cartesi/openapi-interfaces#2

**Comment by marcelstanley** [comment]
@gligneul should we set a hard limit for the payload size? Actix-web [defaults to 256Kib](https://docs.rs/actix-web/4.3.1/actix_web/web/struct.PayloadConfig.html#method.limit)

**Comment by gligneul** [comment]
> @gligneul should we set a hard limit for the payload size? Actix-web [defaults to 256Kib](https://docs.rs/actix-web/4.3.1/actix_web/web/struct.PayloadConfig.html#method.limit)

The limit should be greater or equal to the cartesi machine limit.
