### ISSUE TITLE
SupervisorService times out waiting for services to stop

### ISSUE THREAD

**Issue by torives** [cartesi/rollups-node#271]
## 🙂 Expected behavior

When `SupervisorService` receives a SIGINT or a SIGTERM, it should stop all its services within the default time limit (currently 5 seconds).

## 🫠 Actual behavior

`SupervisorService` stops with the message: `ERROR timed out waiting for services to stop`

## 🧪 Minimal test case

1. Build all docker images by running `make docker-build`
2. Execute the node with `make docker-run`
3. Wait a few seconds for all services to start
4. Stop the execution by sending an interrupt signal: `Ctrl+C`

## 🌎 Environment

 I've reproduced this issue using the Docker images and when running locally on my Mac.

## ✔️ Possible solutions

The only service failing to notify its exit is `server-manager`

**Comment by gligneul** [comment]
I confirmed this is happening here in the Docker environment as well.
```
node-1      | ERROR rollups-node: timed out waiting for services to stop
node-1      | ERROR timed out waiting for services to stop
```
