### ISSUE TITLE
Rename env vars after upgrading to rollups-contracts 2.0.0

### ISSUE THREAD

**Issue by torives** [cartesi/rollups-node#304]
## 📚 Context

There will be several changes in nomenclature in the new major version of the rollup contracts, so it is important to keep our related environment variables in sync with the source.

## ✔️ Solution

Update the variables in `Config.toml` to reflect the changes

## 📈 Subtasks

- [ ] Remove `CARTESI_CONTRACTS_HISTORY_ADDRESS`
- [ ] Rename `CARTESI_CONTRACTS_AUTHORITY_ADDRESS` to `CARTESI_CONTRACTS_CONSENSUS_ADDRESS`

**Comment by torives** [comment]
@guidanoli thanks for bringing this to our attention 😉

**Comment by guidanoli** [comment]
Just a side note that this is not really related to the output unification. It was just a simplification on the consensus part of the contracts. :-)

**Comment by marcelstanley** [comment]
Done as part of #377 at 5dcffde

**Comment by guidanoli** [comment]
Why was this closed as not planned?

**Comment by torives** [comment]
> Why was this closed as not planned?

@guidanoli I think Marcel reopened the issue by accident and just closed it again. The actual code is already merged on the `next/2.0` branch.
