### ISSUE TITLE
Some log messages to improve troubleshooting

### ISSUE THREAD

**Issue by endersonmaia** [cartesi/rollups-node#308]
## 📚 Context
While deploying rollups-node, we need to check if everything is ok right after it starts.

I still miss some logs that would be nice to have.

## ✔️ Solution

- [x] Log the rollups-node version when it starts.
- [x] Ensure the rollups-node version matches the Rust services version to avoid confusion
- [x] Log which `AUTH_*` method is being used
- [x] Provide a single line of error for each problem found in the configuration
- [ ] Log all configuration errors at once to avoid multiple node restarts in quick succession
- [x] Use ISO 8601 as the date format

**Comment by gligneul** [comment]
> some internal rust daemons are still being logged as 1.2.0, and that may be confusing

This should be fixed regardless.

> log which AUTH_ method is being used

Makes sense

**Comment by torives** [comment]
@endersonmaia We'll drop the requirement of listing all configuration errors at once. The Node Unit is now focusing on tasks related to the new major 2.0 release, so we'll deprioritize this. Feel free to contribute with a PR, though. I can give you some pointers 😉

**Comment by endersonmaia** [comment]
@torives I converted the list on this issue description to check boxes, could you mark if any of the items are already implemented, then I'll see if I can take one.

**Comment by torives** [comment]
@endersonmaia #322 should solve all of them except the previously mentioned one.
