### ISSUE TITLE
Improve Node Services' configuration generation

### ISSUE THREAD

**Issue by fmoura** [cartesi/rollups-node#309]
## 📚 Context

The Node configuration generation as of today generates specific public methods for each variable, and these methods get them from System Environment. It makes it difficult to configure the services

## ✔️ Solution

Instead of generating specific methods, generate a Configuration Structure with all the variables. This way the Tests are able to construct the same structure with custom values.

**Comment by gligneul** [comment]
This will be replaced by https://github.com/cartesi/rollups-node/issues/325
