### ISSUE TITLE
Implement Input Reader database functionalities

### ISSUE THREAD

**Issue by GMKrieger** [cartesi/rollups-node#349]
## 📚 Context

The validator update (#348) was meant solely for the validator, and did not take any other service into consideration.

The input reader will need additional support to execute its task, and the repository needs to be updated beforehand to accommodate this. We will need to create additional tables, relations, constraints, as well as implement ways to interact with this information in a safe and atomic way.

It's important to bring attention to how we interact with the data to keep the database consistent, as some transactions are only valid if all the parts move accordingly.

## ✔️ Solution

The input reader functionalities do not require an update on the database model, as of the moment of writing this issue (2024-06-21).

The input reader PR (#451) has an interface on how it expects to interact with the database, and will be implemented as requested.

## 📈 Subtasks

- [x] Implement necessary repository functions
- [x] Create tests for the new functions

**Comment by marcelstanley** [comment]
Done at #512
