### ISSUE TITLE
Evaluate the use of `go-ethereum` as an alternative for the Dispatcher implementation

### ISSUE THREAD

**Issue by marcelstanley** [cartesi/rollups-node#353]
Along the experiment, we shall:

- [x] Review fundamentals of reorgs
- [x] Check logic behind state-fold handling of reorgs in the rust implementation of the dispatcher
- [x] Create prototype in Go
  - [x] Retrieve only finalized blocks
  - [x] Poll for logs every 5 seconds
- [x] Run code against sepolia
  - [x] Perform cost estimation
  - [x] Measure traffic
  - [x] Compare results with current solution

**Comment by marcelstanley** [comment]
A strategy for handling reorgs may be found at https://github.com/ethereum/go-ethereum/issues/26953#issuecomment-1735647669

**Comment by gligneul** [comment]
I think that for the first version, we should focus on reading finalized blocks so we don't have to worry about reorgs.

**Comment by marcelstanley** [comment]
Prototype available at branch [feat/input-reader-prototype](https://github.com/cartesi/rollups-node/tree/feat/input-reader-prototype).

After running the code on both _infura_ and _alchemy_ against _sepolia_, we got around 700 requests/hour, which would amount to approximately 16.8K requests/day.

Such request rate falls well under the limit of daily requests for both [Infura](https://app.infura.io/settings/payment) (100,000 requests/day) and [Alchemy](https://docs.alchemy.com/reference/pricing-plans) (12,000,000 requests/month).

@gligneul FYI

**Comment by gligneul** [comment]
How does that compare to the current node code? Also, what about traffic? What about the compute unit usage? https://docs.alchemy.com/reference/compute-units

**Comment by tuler** [comment]
> Prototype available at branch [feat/input-reader-prototype](https://github.com/cartesi/rollups-node/tree/feat/input-reader-prototype).

Does this use [eth_getFilterChanges](https://www.quicknode.com/docs/ethereum/eth_getFilterChanges)?

**Comment by marcelstanley** [comment]
> Does this use [eth_getFilterChanges](https://www.quicknode.com/docs/ethereum/eth_getFilterChanges)?

Not really. This code relies on go-ethereum's `ethclient` infrastructure, which does not use `eth_getFilterChanges`. It seems [they do not plan to add support for such method in the near future](https://github.com/ethereum/go-ethereum/issues/27315).

In this first prototype, we use a go-ethereum `Filterer` object that uses [`eth_getLogs`](https://www.quicknode.com/docs/ethereum/eth_getLogs) for retrieving events. We narrow down the blocks to be looked at by continually updating the `fromBlock` and `toBlock` parameters according to the latest `finalized` block available to only fetch new events.

**Comment by marcelstanley** [comment]
Notice that the code does not filter for DApp addresses when retrieving logs. That's by design as I deemed this to not be relevant while measuring the amount of requests made to the provider.

**Comment by marcelstanley** [comment]
> It seems [they do not plan to add support for such method in the near future](https://github.com/ethereum/go-ethereum/issues/27315).

Sorry for the confusion. I was referring only to their ethereum client implementation.

They do support `getFilterChanges` in their Filter API, though.

**Comment by marcelstanley** [comment]
After some discussion, we decided to move forward with a code that:

1. Retrieves all previous events upon start, from a genesis block to the most recent finalized block
2. Subcribe to `newHead` but retrieves only new events from finalized blocks
