### ISSUE TITLE
Document manual tests

### ISSUE THREAD

**Issue by torives** [cartesi/rollups-node#382]
## 📚 Context
So far each node version was partially validated by several manual tests before release. As we change the node's internals on the road to version 2.0, we want to register these tests to automate them as soon as possible.

## ✔️ Solution
These are our current manual tests:
### Retrieving state through the GraphQL API
The GraphQL API is the main interaction between the node and its clients, so it is imperative to assert that it is possible to retrieve the node's inputs and outputs. Reports are set aside (for now) as they are only meant for debugging purposes.
- Get inputs using the GraphQL API
- Get notices using the GraphQL API
- Get vouchers using the GraphQL API
### Retrieving state through the Inspect API 
The GraphQL API is the main interaction, but not the only one. So we also must ensure the Inspect API is working as well.
- Send inspect request with GET
- Send inspect request with POST
### Finishing Epochs
By finishing an epoch we are exercising most of the node's code, as proofs and claims are generated (or not) in the process.
- Finish an epoch and send a new input
- Finish an epoch after an empty epoch
- Finish an epoch, get proofs using the GraphQL API, and validate a notice
- Finish an epoch, get proofs using the GraphQL API, and execute a voucher

**Comment by marcelstanley** [comment]
Add a test for guaranteeing that inputs sent to an application before its actual deployment are processed correctly
