### ISSUE TITLE
`CARTESI_FEATURE_DISABLE_CLAIMER` is a bad name

### ISSUE THREAD

**Issue by renan061** [cartesi/rollups-node#426]
## 📚 Context

`CARTESI_FEATURE_DISABLE_CLAIMER` is somewhat of a bad name.
Specially taken into consideration the `EXPERIMENTAL_SUNODO` variables.

## ✔️ Solution

We should either rename the variable or clarify in the configuration documentation
that it serves as to enable a reader-only mode.

## 📈 Subtasks

- [ ] Evaluate whether we could either merge the `CLAIMER` and `SUNODO_VALIDATOR` together or better clarify their usade
- [ ] Implement changes
- [ ] Update docs

**Comment by renan061** [comment]
@endersonmaia 's suggestion that I agree with:

> I don't remember where/when, but I did suggest about normalizing the names to bool _DISABLED and _ENABLED suffixes to imply state instead of ENABLE and DISABLEimplying action.
> We use both and it may confuse.
> 
> CARTESI_FEATURE_**DISABLE**\_CLAIMER
> CARTESI_EXPERIMENTAL_SUNODO_VALIDATOR_**ENABLED**

**Comment by marcelstanley** [comment]
> @endersonmaia 's suggestion that I agree with:
> 
> > I don't remember where/when, but I did suggest about normalizing the names to bool `_DISABLED` and `_ENABLED` suffixes to imply state instead of `ENABLE` and `DISABLE` implying action.
> > We use both and it may confuse.
> > CARTESI_FEATURE_**DISABLE**_CLAIMER
> > CARTESI_EXPERIMENTAL_SUNODO_VALIDATOR_**ENABLED**

Created  #427 for the normalization

**Comment by marcelstanley** [comment]
To be covered at #539
