### ISSUE TITLE
Restoring the `linux/arm64` platform in the CI

### ISSUE THREAD

**Issue by renan061** [cartesi/rollups-node#439]
## 📚 Context

As part of installing the cartesi-machine in the CI we commented out the `linux/arm64` platform
in `build/docker-bake.platforms.hcl`. We should revert this before merging `next/2.0` into `main`.

We did this because `libarchive13` (required by `xgenext2fs` in the emulator-devel stage) is not available for arm64.

## ✔️ Solution

The machine team could release a `xgenext2fs` for arm, but that is not necessary.
Instead, we need to discriminate which stages/targets get built for which platforms.

**Comment by tuler** [comment]
xgenext2fs has a arm64 release at https://github.com/cartesi/genext2fs/releases/download/v1.5.6/xgenext2fs_arm64.deb

**Comment by renan061** [comment]
I don't know why I reached the conclusion that both `xgenext2fs` and `libarchive13` were not available for `arm64`.
Thanks for correcting this mental lapse, @tuler!

**Comment by marcelstanley** [comment]
Done as part of #435
