### ISSUE TITLE
Lock postgraphile dependencies

### ISSUE THREAD

**Issue by marcelstanley** [cartesi/rollups-node#442]
## 📚 Context

Postgraphile dependencies installed  via Dockerfile have no version lock.

## ✔️ Solution

Add full version to dependencies as _originally posted by @endersonmaia in https://github.com/cartesi/rollups-node/pull/401#discussion_r1627516742_ to make container reproducibility achievable:

```suggestion
npm install -g postgraphile@4.13
npm install -g --save @graphile-contrib/pg-simplify-inflector@6.1
```

**Comment by GMKrieger** [comment]
Done in #450
