### ISSUE TITLE
Fix clippy warnings on dispatcher and  state-fold

### ISSUE THREAD

**Issue by marcelstanley** [cartesi/rollups-node#46]
## 📚 Context

As mentioned at rollups-node #37, the following warnings were further deferred due to upcoming refactoring to `dispatcher` and `state-fold`:

- [*too_many_arguments*](https://rust-lang.github.io/rust-clippy/master/index.html#/too_many_arguments), disabled at [93ac09](https://github.com/cartesi/rollups/commit/93ac098f3760d636228c70bfcf6d6c4b8aec6486)
- [*module_inception*](https://rust-lang.github.io/rust-clippy/master/index.html#/module_inception), disabled at [e81541e](https://github.com/cartesi/rollups/pull/159/commits/e81541eccacf881ced5a5a1e9c46b523579ccdb2) - affects code generated via `state-fold-types`.

## ✔️ Solution

Adjust the code to meet the requirements for both lints if they're still present after the refactoring.

## 📈 Subtasks

Meet requirements for:
- [ ] Fix *too_many_arguments*
- [ ] Fix *module_inception*

**Comment by gligneul** [comment]
We won't do that because we will move to a new architecture in https://github.com/cartesi/rollups-node/issues/101
