### ISSUE TITLE
Create update procedure for v1.5

### ISSUE THREAD

**Issue by marcelstanley** [cartesi/rollups-node#461]
## 📚 Context

Release `v1.5` comes with a breaking change in the way epochs are calculated when compared to any previous `v1.x` release.

Such change objectively fixes #432 and, in doing so, requires that existing applications upgrade their version of the node and their instances of the [History contract](https://github.com/cartesi/rollups-contracts/blob/v1.4.0/onchain/rollups/contracts/history/History.sol) to have their history rewritten.

## ✔️ Solution

Define and test all steps required for upgrading an application from [v1.4](https://github.com/cartesi/rollups-node/releases/tag/v1.4.0) to v1.5 if needed. 

Such procedure should:
- describe how to upgrade the version of the node
- describe the steps to be taken by the application owner to prepare the application to have its history rewritten
- describe how to check that the application state was kept after the upgrade is done
- identify potential issues and propose solutions
- list the requirements to follow the procedure (e.g.: tools, permissions etc)
- provide examples of step success where applicable.
- test on an environment that replicates "production" (if possible).
- add a warning that "History contract holds claims for several applications. Changing the History affects all applications managed by that History.

> [!NOTE]  
> New history instances can be created with [`HistoryFactory.newHistory()`](https://github.com/cartesi/rollups-contracts/blob/e8a2d82bc51167086e7928b9a6aced0d62c96cf8/onchain/rollups/contracts/history/HistoryFactory.sol#L24)

> [!NOTE]  
> In order to update an application history, is necessary to call [`Authority.setHistory()`](https://github.com/cartesi/rollups-contracts/blob/e8a2d82bc51167086e7928b9a6aced0d62c96cf8/onchain/rollups/contracts/consensus/authority/Authority.sol#L65)
## 📈 Subtasks

- [ ] TBD

## ✅ Definition of Done

- [ ] Migration guide created (MD document under docs folder with a link from the main README)
- [ ] Reproduceable steps demonstrating a test application has been successfully upgraded and its state has been kept after the upgrade

**Comment by tuler** [comment]
Notice that `History` contract holds claims for several applications.
Changing the History affects all applications managed by that History.

**Comment by marcelstanley** [comment]
Done at #507
