### ISSUE TITLE
Create and Test Migration Procedure for Applications from v1.4 to v1.5

### ISSUE THREAD

**Issue by vfusco** [cartesi/rollups-node#471]
Description:

We need to create and test a migration procedure for applications currently running on version 1.4 if they need it.

Things that should be considered:

- Outline the step-by-step process for migrating from v1.4 to v1.5, identifying potential issues and proposing solutions.
- List the requirements to follow the procedure (e.g.: tools, permissions etc)
- Provide examples of step success where applicable.
- Test on an environment that replicates "production" (if possible).

**Comment by marcelstanley** [comment]
Merged into #461
