### ISSUE TITLE
Unify DApp configuration across services

### ISSUE THREAD

**Issue by renan061** [cartesi/rollups-node#50]
## 📚 Context

Each service has its own way of setting up DApp deployment data.

## ✔️ Solution

We should create a crate unifies DApp deployment data configuration.
We could utilize some of DAppMetadata from `rollups-events` for this.

**Comment by torives** [comment]
Which data are we talking about? Is it only the chain id and DApp address already on `DAppMetadata` or is there more?

Although I'm unfamiliar with the code, there are many deployment-related structs in the `types` crate.

**Comment by gligneul** [comment]
We must unify the DAppMetadata [1] and the DappDeployment [2] structs. The DApp address is initialized from the `dapp.json` file for both structs, and this code is replicated in multiple places. We need to think of a better way of organizing this configuration code.

[1] https://github.com/cartesi/rollups-node/blob/next/offchain/rollups-events/src/rollups_stream.rs#L12
[2] https://github.com/cartesi/rollups-node/blob/next/offchain/types/src/deployment_files.rs#L9

**Comment by gligneul** [comment]
This should be addressed in https://github.com/cartesi/rollups-node/issues/88
