### ISSUE TITLE
Configure the authority-claimer for proper release

### ISSUE THREAD

**Issue by renan061** [cartesi/rollups-node#51]
## 📚 Context

We need to add the authority-claimer to the Dockerfile, [docker-bake.hcl](https://github.com/cartesi/rollups-node/blob/next/docker-bake.hcl), CI workflow, and README.

**Comment by marcelstanley** [comment]
I believe neither `Dockerfile` nor `docker-bake-hcl` need updating. Just #43 would be necessary

**Comment by gligneul** [comment]
Replaced by https://github.com/cartesi/rollups-node/issues/131
