### ISSUE TITLE
Do not create overlapping claims events on advance-runner

### ISSUE THREAD

**Issue by marcelstanley** [cartesi/rollups-node#537]
## 📚 Context

A duplicate rollups claim was detected on an application running rollups-node v1.5.0-rc1 along with sunodo experimental external claimer. 

Output from the redis stream:
```
5) 1) "1720358484614-0"
   2) 1) "payload"
      2) "{\"dapp_address\":\"69b9af2474d8dda0329be8da831ce063a4636587\",\"epoch_index\":4,\"epoch_hash\":\"162f158d132cdd6cbefbe3b2cf229af182905ff7034445dd0b6ad013772c4a76\",\"first_index\":27,\"last_index\":31}"
6) 1) "1720454043072-0"
   2) 1) "payload"
      2) "{\"dapp_address\":\"69b9af2474d8dda0329be8da831ce063a4636587\",\"epoch_index\":5,\"epoch_hash\":\"162f158d132cdd6cbefbe3b2cf229af182905ff7034445dd0b6ad013772c4a76\",\"first_index\":27,\"last_index\":31}"
```

> The full contents can be found at [1.5.0-rc1-advance-runner-duplicate-clalims.txt](https://github.com/user-attachments/files/16418936/1.5.0-rc1-advance-runner-duplicate-clalims.txt)

## ✔️ Solution

Initial analysis point to a faulty check on the advance-runner, where the first and input indexes are not checked before the claim is produced, allowing for duplicates to be created.

There was no ramifications to this bug as the claimer itself is able to handle duplicates claimes.

However, we should add a more robust test, a counterpart for the claim checker, which would check for overlapping input indexes along with the verification of epoch index before a claim can be submitted to the claims stream.

## 📈 Subtasks

- [ ] Test for overlapping input indexes
- [ ] Update tests

**Comment by GMKrieger** [comment]
Done in #523
