### ISSUE TITLE
Simplify Postgres connection definition

### ISSUE THREAD

**Issue by tuler** [cartesi/rollups-node#55]
## 📚 Context

Today we are handling the definition of the connection string used by the services that have access to the database, namely the graphql-server and the indexer.

We had a few issues in the past with that approach, and implemented fixes, but not in the right way.

As a first example, the password was being added to the connection string, and leaking in the log of the application, which made us fix by explicitly redacting if from the log.

Another example is how we implemented the feature request of reading the password from a file.
Reading the password from a file is the recommended way of doing it, because environment variables are much more prone to leaking. However it should be the Postgres driver the one responsible for reading the file, which it does.
The password file is expected to be in a particular format though, as specified by the [documentation](https://www.postgresql.org/docs/current/libpq-pgpass.html).

One example of such file content is below:

```
*:*:*:*:my_password
```

And not simply the password, as we implemented.

These have consequences on the deployment we do on Kubernetes, and with this issue we can't handle the database password securely throughout all services.

## ✔️ Solution

It should be enough to simply forward to the `PgConnection` instantiation a connection string directly specified in the config, as a simple string. No need for parsing, formatting, or reading from env variables.

Let the pg driver handle all that. The rust pg driver is a binding to the C driver, and the connection calls the `PQconnectdb` driver method, which implements the logic of env variables as described in this [documentation](https://www.postgresql.org/docs/current/libpq-envars.html).

So if we use an empty string as connection string, it will use the env variables described in that document, including the `PGPASSFILE`, which is the safe way of specifying the database password.

**Comment by tuler** [comment]
Reopening of https://github.com/cartesi-corp/rollups/issues/868
@endersonmaia

**Comment by gligneul** [comment]
Makes sense. I will prioritize this for the next release.

**Comment by endersonmaia** [comment]
I think we should only expect to read in the `PGPASSFILE` in the format `hostname:port:database:username:password` if this environment variable exists, or a file at `$HOME/.pgpass` exists. And this should be handled by the postgres lib.

On the other hand, if the user provide the environment variable `POSTGRES_PASSWORD_FILE` for the `indexer`, for example, we should read its contents to recover only the password from there.

**Comment by tuler** [comment]
No, we don’t need to read the file at all, or care about its format. The driver will do it.

**Comment by gligneul** [comment]
The idea is to replace our current config options with the Postgres driver, correct?
