### ISSUE TITLE
dispatcher should accept override history_address and authority_address rollups deployent configuration

### ISSUE THREAD

**Issue by endersonmaia** [cartesi/rollups-node#70]
## 📚 Context

So that I can use AWS KMS keys to sign/verify transactions, I need to deploy the Auhority and History contracts using the same KMS key.

When I configure a validator-node's dispatcher, the `history_address` and `authority_address` configurations are read from the `--rollups-deployment-file` CLI argument, and a file that could be used as a value for that argument is currently being distributed within the rollups-dispather container image at `/opt/cartesi/share/deployments/$network.json`.

## ✔️ Solution

It should be possible to override only these parameters (`history_address`, `authority_address`) via CLI argument to reuse the rollups deployment file already distributed but override only those addresses.

**Comment by gligneul** [comment]
This should be done in https://github.com/cartesi/rollups-node/issues/88
