### ISSUE TITLE
Inconsistent serialization of BigInt GraphQL scalar

### ISSUE THREAD

**Issue by tuler** [cartesi/rollups-node#74]
## 🙂 Expected behavior

The GraphQL schema language supports the scalar types of String, Int, Float, Boolean, and ID.
For other types it supports custom Scalars. BigInt is one of those.

The implementation of custom Scalars are typically left to the GraphQL implementation, which in general provide some sort of [coercing implementation](https://www.graphql-java.com/documentation/scalars/#coercing-values) method.

In general BigInt types are serialized to strings. One of the reasons is that JSON does not support coercion of number literals to the native B[igInt](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt#bigint_coercion) type.

Other blockchain indexers that provide a GraphQL interface coerce BigInt to string.
TheGraph [supports BigInt](https://thegraph.com/docs/en/developing/creating-a-subgraph/#built-in-scalar-types) and always serialize as string.
Subsquid also [supports BigInt](https://docs.subsquid.io/query-squid/queries/#supported-scalar-types) and always serialize as string.

We should follow our schema definition and also always serialize BigInt as string.

We currently use BigInt in two locations:

```graphql
"Request submitted to the application to advance its state"
type Input {
  ...
  "Timestamp associated with the input submission, as defined by the base layer's block in which it was recorded"
  timestamp: BigInt!
  "Number of the base layer block in which the input was recorded"
  blockNumber: BigInt!
  ...
}
```

## 🫠 Actual behavior

It looks like from my understanding that the server is serializing the value depending on the value itself.
If it's less than a i32 it is serializing as int. Otherwise it serializes as string.
https://github.com/cartesi/rollups-node/blob/1da90a45bf43e728b7a48e45d4dc1cf49f12f5ac/offchain/graphql-server/src/schema/scalar.rs#L123

We should not serialize conditionally on the value. Otherwise it can be very confusing for the parser, who will also need to conditionally parse without the proper context.

## 🧪 Minimal test case

Query the server at
https://0x9f12d4365806fc000d6555acb85c5371b464e506.sepolia.rollups.staging.cartesi.io/graphql

```graphql
{
  inputs {
    edges {
      node {
        timestamp
        blockNumber
      }
    }
  }
}
```

## 🌎 Environment

Rollups 1.0.0

## ✔️ Possible solutions

We should stick to the type definition.
If type definition is `BigInt` coerce as string.
If type definition is `Int` coerce as number.

**Comment by gligneul** [comment]
Solved by https://github.com/cartesi/rollups/pull/232
