### ISSUE TITLE
Wrong timestamp of Input

### ISSUE THREAD

**Issue by tuler** [cartesi/rollups-node#75]
## 🙂 Expected behavior

`Input.timestamp` in the GraphQL server should be number of seconds since epoch.

## 🫠 Actual behavior

The value is being [divided by 1000](https://github.com/cartesi/rollups-node/blob/1da90a45bf43e728b7a48e45d4dc1cf49f12f5ac/offchain/indexer/src/conversions.rs#L17) by assuming the value that comes from the blockchain was in milliseconds, when in fact it's in seconds.

## 🧪 Minimal test case

Query the server at
https://0x9f12d4365806fc000d6555acb85c5371b464e506.sepolia.rollups.staging.cartesi.io/graphql

```graphql
{
  inputs {
    edges {
      node {
        timestamp
      }
    }
  }
}
```

## 🌎 Environment

Rollups 1.0.0

## ✔️ Possible solutions

Fix by assuming the value is in seconds while converting to the [NaiveDateTime](https://docs.rs/chrono/latest/chrono/naive/struct.NaiveDateTime.html#method.from_timestamp) data type.
Or even better, remove completely the `NaiveDateTime` data type and leave the original `i64` type.
Do we need a `NaiveDateTime` to do any date handling?

**Comment by gligneul** [comment]
I confirmed that this was introduced in 0.9 when we refactored the indexer.

**Comment by gligneul** [comment]
Fixed by https://github.com/cartesi/rollups/pull/231
