### ISSUE TITLE
dispatcher /metrics endpoint metric documentation differs from metric name

### ISSUE THREAD

**Issue by endersonmaia** [cartesi/rollups-node#78]
## 🙂 Expected behavior

Metrics names over the dispatcher's `/metrics` endpoint should match the documented metric name.

## 🫠 Actual behavior

Missing `_total` at the commented (documented) part of the metric.

```
❯ curl http://127.0.0.1:8081/metrics
# HELP cartesi_rollups_dispatcher_claims_sent Counts the number of claims sent.
# TYPE cartesi_rollups_dispatcher_claims_sent counter
# HELP cartesi_rollups_dispatcher_advance_inputs_sent Counts the number of <advance_input>s sent.
# TYPE cartesi_rollups_dispatcher_advance_inputs_sent counter
cartesi_rollups_dispatcher_advance_inputs_sent_total{chain_id="11155111",dapp_address="9f12d4365806fc000d6555acb85c5371b464e506"} 4
# HELP cartesi_rollups_dispatcher_finish_epochs_sent Counts the number of <finish_epoch>s sent.
# TYPE cartesi_rollups_dispatcher_finish_epochs_sent counter
cartesi_rollups_dispatcher_finish_epochs_sent_total{chain_id="11155111",dapp_address="9f12d4365806fc000d6555acb85c5371b464e506"} 1
# EOF
```

## 🌎 Environment

`rollups-node:1.0.0`

## ✔️ Possible solutions

Match the names between metrics and their documentation.

**Comment by gligneul** [comment]
This is generated automatically by the prometheus library.

**Comment by gligneul** [comment]
@endersonmaia it doesn't work, the library that we use always add the `_total` suffix:
```
# TYPE cartesi_rollups_dispatcher_advance_inputs_sent_total counter
cartesi_rollups_dispatcher_advance_inputs_sent_total_total{chain_id="31337",dapp_address="70ac08179605af2d9e75782b8decdd3c22aa4d0c"} 1
```

**Comment by gligneul** [comment]
The library we use doesn't support the requested feature [1]. I will close this issue; if this is considered a blocker, we can work around it in another one.

[1] https://github.com/prometheus/client_rust/issues/51
