### ISSUE TITLE
Log version in node startup

### ISSUE THREAD

**Issue by gligneul** [cartesi/rollups-node#8]
## 📚 Context

Given the log, we want to know which version of the node is running. This is particularly useful when someone sends us a log with a problem.

## ✔️ Solution

This could be done with the help of the following [built crate](https://docs.rs/built/latest/built/).

## 📈 Subtasks

Apply the modifications to all services:

- [x] state server
- [x] dispatcher
- [x] autority-claimer
- [x] advance runner
- [x] inspect server
- [x] graphql server
- [x] host runner

**Comment by fmoura** [comment]
@gligneul Built has some information about the build that we could log. But I think the more consistent ones are "package version" and "build time" 

There is a "git version", "git branch"  that are available if the build is from a git repo, which is not the case when building using Docker Buildx Bake.

Should I stick to only "package version" for now?

**Comment by gligneul** [comment]
Yes, only the package version is fine. I don't like the idea of using build time.
