### ISSUE TITLE
Create Go supervisor

### ISSUE THREAD

**Issue by torives** [cartesi/rollups-node#80]
## 📚 Context

Running a node right now requires the orchestration of several Docker containers. For testing, running locally, and/or deploying in a VPS a simpler option is desirable.

Original issue/discussion: #26

## ✔️ Solution

Create a single binary to execute all of our services. All service configuration should be done via environment variables, as the binary will have just a single parameter defining its execution mode: reader, validator, full (reader+validator), or host.

It will forward each service's stdout and stderr to its own stdout and stderr, similar to what is currently done when running the node using the `docker-compose.yml` file.

Although `server-manager` is not a service built in this repository, it will also be executed by the binary: it will assume it is installed in the system and available in the PATH.

It will also assume the Redis, PostgreSQL, and Hardhat services are already running and ready to connect by the time it starts.

## 📈 Subtasks

- [x] #65
- [x] #91
- [x] #96
- [x] #108
- [x] #116
- [x] #88
- [x] #125
- [x] #97
- [x] #139
- [x] #140
- [x] #180
- [x] #179
- [x] #177
- [x] #193
- [x] #221
- [x] #241
  - `/graphql`, `/inspect`, `/rollups` (host-mode), `/metrics` (dispatcher)
  - See https://github.com/elazarl/goproxy
  - We should expose only the proxy port once we have the proxy. Addresses other than the port should be 127.0.0.1.
  - The proxy address should be 127.0.0.1 by default, and we should have an env var to configure it. This way, the node doesn't bind to a public address, which would be an unsafe default.
- [x] #198
- [x] #222
  - See: https://github.com/gligneul/eggroll/blob/main/internal/dev/signal.go#L14 and https://github.com/gligneul/eggroll/blob/main/internal/dev/dev.go#L27
- [x] #200

**Comment by gligneul** [comment]
We could rename `host` mode to `backendless` mode, following the idea of sunodo.

**Comment by endersonmaia** [comment]
> Create a single binary to execute all of our services....

> It will forward each service's stdout and stderr to its own stdout and stderr ...

Are you planning to create another process/service supervisor? Why not reuse some existing software that already does this?

For sunodo/rollups-node, we're using [s6-overlay,](https://github.com/just-containers/s6-overlay), but there are a lot of other options if you think `s6` is not a fit.

The choice for `s6` was 'cause it's made for running inside containers and it's very light.

**Comment by endersonmaia** [comment]
Since you're considering migrating some code to golang, maybe this [supervisord golang implementation](https://github.com/ochinchina/supervisord) is an option.

**Comment by gligneul** [comment]
We want to do something much simpler than a supervisor. And, as we rewrite code in Go, we will replace the external binaries with Go packages. So, in the end, there won't be any "supervisor" code left.

**Comment by gligneul** [comment]
Suggestion for the supervisor code using goroutines: https://gist.github.com/gligneul/dafa46f3e778888e108da13aa2d89d17
